"""add keylog mouse

Revision ID: 00f73f48c894
Revises: d16ddaee6be5
Create Date: 2025-09-21 10:32:50.122013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00f73f48c894'
down_revision: Union[str, Sequence[str], None] = 'd16ddaee6be5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keylog', sa.Column('words_per_minute', sa.Float(), nullable=True))
    op.add_column('keylog', sa.Column('typing_rhythm_consistency', sa.Float(), nullable=True))
    op.add_column('keylog', sa.Column('mouse_speed', sa.Float(), nullable=True))
    op.add_column('keylog', sa.Column('mouse_accuracy', sa.Float(), nullable=True))
    op.add_column('keylog', sa.Column('mouse_jerkiness', sa.Float(), nullable=True))
    op.add_column('keylog', sa.Column('raw_x_sequence', sa.String(), nullable=True))
    op.add_column('keylog', sa.Column('raw_y_sequence', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('keylog', 'raw_y_sequence')
    op.drop_column('keylog', 'raw_x_sequence')
    op.drop_column('keylog', 'mouse_jerkiness')
    op.drop_column('keylog', 'mouse_accuracy')
    op.drop_column('keylog', 'mouse_speed')
    op.drop_column('keylog', 'typing_rhythm_consistency')
    op.drop_column('keylog', 'words_per_minute')
    # ### end Alembic commands ###
