"""add validation response

Revision ID: 4f8dd0588c52
Revises: 872ef1d2d6d9
Create Date: 2025-09-15 10:46:51.482778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f8dd0588c52'
down_revision: Union[str, Sequence[str], None] = '872ef1d2d6d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.String(length=100), nullable=False),
    sa.Column('answer', sa.Enum('FOCUS_TASK', 'FOCUS_METHOD', 'THINK_OUTSIDE_TASK', name='validationanswerenum'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_email'], ['users.user_email'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation_responses')
    # ### end Alembic commands ###
