"""add faculty column

Revision ID: 67d588b3e4ad
Revises: 00f73f48c894
Create Date: 2025-10-02 15:41:32.423331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67d588b3e4ad'
down_revision: Union[str, Sequence[str], None] = '00f73f48c894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('faculty', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'faculty')
    # ### end Alembic commands ###
