"""init database

Revision ID: 74760e443857
Revises: 
Create Date: 2025-09-03 19:44:04.681345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74760e443857'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keylog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('keystroke_count', sa.Integer(), nullable=True),
    sa.Column('left_click_count', sa.Integer(), nullable=True),
    sa.Column('right_click_count', sa.Integer(), nullable=True),
    sa.Column('scroll_up', sa.Integer(), nullable=True),
    sa.Column('scroll_down', sa.Integer(), nullable=True),
    sa.Column('space_count', sa.Integer(), nullable=True),
    sa.Column('error_rate', sa.Float(), nullable=True),
    sa.Column('mean_dwell_time_ms', sa.Float(), nullable=True),
    sa.Column('std_dev_dwell_time_ms', sa.Float(), nullable=True),
    sa.Column('mean_flight_time_ms', sa.Float(), nullable=True),
    sa.Column('std_dev_flight_time_ms', sa.Float(), nullable=True),
    sa.Column('mean_digraph_time_ms', sa.Float(), nullable=True),
    sa.Column('std_dev_digraph_time_ms', sa.Float(), nullable=True),
    sa.Column('pause_count', sa.Integer(), nullable=True),
    sa.Column('mean_pause_duration_ms', sa.Float(), nullable=True),
    sa.Column('mean_burst_length', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keylog_user_email'), 'keylog', ['user_email'], unique=False)
    op.create_table('posture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('capture_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('front_image_link', sa.String(), nullable=True),
    sa.Column('side_image_link', sa.String(), nullable=True),
    sa.Column('overhead_image_link', sa.String(), nullable=True),
    sa.Column('chair_state_armrest_adjustable', sa.Boolean(), nullable=True),
    sa.Column('chair_state_armrest_height_from_seat', sa.Float(), nullable=True),
    sa.Column('chair_state_armrest_surface_hard', sa.Boolean(), nullable=True),
    sa.Column('chair_state_armrests_too_wide', sa.Boolean(), nullable=True),
    sa.Column('chair_state_back_contact_percentage', sa.Float(), nullable=True),
    sa.Column('chair_state_backrest_adjustable', sa.Boolean(), nullable=True),
    sa.Column('chair_state_elbow_angle', sa.Float(), nullable=True),
    sa.Column('chair_state_feet_on_floor', sa.Boolean(), nullable=True),
    sa.Column('chair_state_foot_contact_percentage', sa.Float(), nullable=True),
    sa.Column('chair_state_forearm_support_contact', sa.Boolean(), nullable=True),
    sa.Column('chair_state_gap_behind_knee', sa.Float(), nullable=True),
    sa.Column('chair_state_height_adjustable', sa.Boolean(), nullable=True),
    sa.Column('chair_state_knee_angle', sa.Float(), nullable=True),
    sa.Column('chair_state_knee_clearance', sa.Float(), nullable=True),
    sa.Column('chair_state_leg_room_width', sa.Float(), nullable=True),
    sa.Column('chair_state_lumbar_contact', sa.Boolean(), nullable=True),
    sa.Column('chair_state_lumbar_curve_match', sa.Float(), nullable=True),
    sa.Column('chair_state_pan_depth_adjustable', sa.Boolean(), nullable=True),
    sa.Column('chair_state_recline_angle', sa.Float(), nullable=True),
    sa.Column('chair_state_shoulder_elevation', sa.Boolean(), nullable=True),
    sa.Column('chair_state_thigh_pressure', sa.Boolean(), nullable=True),
    sa.Column('chair_state_thigh_support_length', sa.Float(), nullable=True),
    sa.Column('chair_state_work_surface_too_high', sa.Boolean(), nullable=True),
    sa.Column('final_scores_bc_combined_score', sa.Integer(), nullable=True),
    sa.Column('final_scores_final_rosa_score', sa.Integer(), nullable=True),
    sa.Column('final_scores_section_a_score', sa.Integer(), nullable=True),
    sa.Column('final_scores_section_b_score', sa.Integer(), nullable=True),
    sa.Column('final_scores_section_c_score', sa.Integer(), nullable=True),
    sa.Column('monitor_phone_state_has_glare', sa.Boolean(), nullable=True),
    sa.Column('monitor_phone_state_has_neck_twist', sa.Boolean(), nullable=True),
    sa.Column('monitor_phone_state_monitor_consecutive_minutes', sa.Integer(), nullable=True),
    sa.Column('monitor_phone_state_monitor_too_far', sa.Boolean(), nullable=True),
    sa.Column('monitor_phone_state_monitor_too_high', sa.Boolean(), nullable=True),
    sa.Column('monitor_phone_state_monitor_too_low', sa.Boolean(), nullable=True),
    sa.Column('monitor_phone_state_no_doc_holder', sa.Boolean(), nullable=True),
    sa.Column('monitor_phone_state_no_hands_free', sa.Boolean(), nullable=True),
    sa.Column('monitor_phone_state_phone_consecutive_minutes', sa.Integer(), nullable=True),
    sa.Column('monitor_phone_state_phone_too_far', sa.Boolean(), nullable=True),
    sa.Column('monitor_phone_state_use_neck_shoulder_hold', sa.Boolean(), nullable=True),
    sa.Column('mouse_keyboard_state_deviation_while_typing', sa.Boolean(), nullable=True),
    sa.Column('mouse_keyboard_state_keyboard_consecutive_minutes', sa.Integer(), nullable=True),
    sa.Column('mouse_keyboard_state_keyboard_duration_hours', sa.Integer(), nullable=True),
    sa.Column('mouse_keyboard_state_keyboard_platform_non_adjustable', sa.Boolean(), nullable=True),
    sa.Column('mouse_keyboard_state_keyboard_too_high', sa.Boolean(), nullable=True),
    sa.Column('mouse_keyboard_state_mouse_consecutive_minutes', sa.Integer(), nullable=True),
    sa.Column('mouse_keyboard_state_mouse_duration_hours', sa.Integer(), nullable=True),
    sa.Column('mouse_keyboard_state_mouse_keyboard_on_different_surfaces', sa.Boolean(), nullable=True),
    sa.Column('mouse_keyboard_state_palmrest_in_front_of_mouse', sa.Boolean(), nullable=True),
    sa.Column('mouse_keyboard_state_pinch_grip_on_mouse', sa.Boolean(), nullable=True),
    sa.Column('mouse_keyboard_state_reaching_to_mouse', sa.Boolean(), nullable=True),
    sa.Column('mouse_keyboard_state_reaching_to_overhead_items', sa.Boolean(), nullable=True),
    sa.Column('mouse_keyboard_state_wrists_extended', sa.Boolean(), nullable=True),
    sa.Column('score_a_results_armrest_score', sa.Integer(), nullable=True),
    sa.Column('score_a_results_arms_back_axis', sa.Integer(), nullable=True),
    sa.Column('score_a_results_backrest_score', sa.Integer(), nullable=True),
    sa.Column('score_a_results_chair_base_score', sa.Integer(), nullable=True),
    sa.Column('score_a_results_depth_score', sa.Integer(), nullable=True),
    sa.Column('score_a_results_final_score', sa.Integer(), nullable=True),
    sa.Column('score_a_results_height_score', sa.Integer(), nullable=True),
    sa.Column('score_a_results_seat_pan_axis', sa.Integer(), nullable=True),
    sa.Column('score_b_results_final_b_score', sa.Integer(), nullable=True),
    sa.Column('score_b_results_monitor_score', sa.Integer(), nullable=True),
    sa.Column('score_b_results_phone_score', sa.Integer(), nullable=True),
    sa.Column('score_c_results_final_c_score', sa.Integer(), nullable=True),
    sa.Column('score_c_results_keyboard_score', sa.Integer(), nullable=True),
    sa.Column('score_c_results_mouse_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_email', 'capture_id', name='uq_posture_user_capture')
    )
    op.create_index(op.f('ix_posture_capture_id'), 'posture', ['capture_id'], unique=False)
    op.create_index(op.f('ix_posture_user_email'), 'posture', ['user_email'], unique=False)
    op.create_table('users',
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index(op.f('ix_posture_user_email'), table_name='posture')
    op.drop_index(op.f('ix_posture_capture_id'), table_name='posture')
    op.drop_table('posture')
    op.drop_index(op.f('ix_keylog_user_email'), table_name='keylog')
    op.drop_table('keylog')
    # ### end Alembic commands ###
