"""add nordic response

Revision ID: 872ef1d2d6d9
Revises: c8a9c5ef2c34
Create Date: 2025-09-05 14:46:08.175791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '872ef1d2d6d9'
down_revision: Union[str, Sequence[str], None] = 'c8a9c5ef2c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nordic_bodymap_response',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('nbm_0', sa.SmallInteger(), nullable=False),
    sa.Column('nbm_1', sa.SmallInteger(), nullable=False),
    sa.Column('nbm_2', sa.SmallInteger(), nullable=False),
    sa.Column('nbm_3', sa.SmallInteger(), nullable=False),
    sa.Column('nbm_4', sa.SmallInteger(), nullable=False),
    sa.Column('nbm_5', sa.SmallInteger(), nullable=False),
    sa.Column('nbm_6', sa.SmallInteger(), nullable=False),
    sa.Column('nbm_7', sa.SmallInteger(), nullable=False),
    sa.Column('nbm_8', sa.SmallInteger(), nullable=False),
    sa.Column('nbm_9', sa.SmallInteger(), nullable=False),
    sa.Column('nbm_10', sa.SmallInteger(), nullable=False),
    sa.Column('nbm_11', sa.SmallInteger(), nullable=False),
    sa.Column('nbm_12', sa.SmallInteger(), nullable=False),
    sa.Column('nbm_13', sa.SmallInteger(), nullable=False),
    sa.Column('nbm_14', sa.SmallInteger(), nullable=False),
    sa.Column('nbm_15', sa.SmallInteger(), nullable=False),
    sa.Column('nbm_16', sa.SmallInteger(), nullable=False),
    sa.Column('nbm_17', sa.SmallInteger(), nullable=False),
    sa.Column('nbm_18', sa.SmallInteger(), nullable=False),
    sa.Column('nbm_19', sa.SmallInteger(), nullable=False),
    sa.Column('nbm_20', sa.SmallInteger(), nullable=False),
    sa.Column('nbm_21', sa.SmallInteger(), nullable=False),
    sa.Column('nbm_22', sa.SmallInteger(), nullable=False),
    sa.Column('nbm_23', sa.SmallInteger(), nullable=False),
    sa.Column('nbm_24', sa.SmallInteger(), nullable=False),
    sa.Column('nbm_25', sa.SmallInteger(), nullable=False),
    sa.Column('nbm_26', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('nbm_0  BETWEEN 1 AND 4'),
    sa.CheckConstraint('nbm_1  BETWEEN 1 AND 4'),
    sa.CheckConstraint('nbm_10 BETWEEN 1 AND 4'),
    sa.CheckConstraint('nbm_11 BETWEEN 1 AND 4'),
    sa.CheckConstraint('nbm_12 BETWEEN 1 AND 4'),
    sa.CheckConstraint('nbm_13 BETWEEN 1 AND 4'),
    sa.CheckConstraint('nbm_14 BETWEEN 1 AND 4'),
    sa.CheckConstraint('nbm_15 BETWEEN 1 AND 4'),
    sa.CheckConstraint('nbm_16 BETWEEN 1 AND 4'),
    sa.CheckConstraint('nbm_17 BETWEEN 1 AND 4'),
    sa.CheckConstraint('nbm_18 BETWEEN 1 AND 4'),
    sa.CheckConstraint('nbm_19 BETWEEN 1 AND 4'),
    sa.CheckConstraint('nbm_2  BETWEEN 1 AND 4'),
    sa.CheckConstraint('nbm_20 BETWEEN 1 AND 4'),
    sa.CheckConstraint('nbm_21 BETWEEN 1 AND 4'),
    sa.CheckConstraint('nbm_22 BETWEEN 1 AND 4'),
    sa.CheckConstraint('nbm_23 BETWEEN 1 AND 4'),
    sa.CheckConstraint('nbm_24 BETWEEN 1 AND 4'),
    sa.CheckConstraint('nbm_25 BETWEEN 1 AND 4'),
    sa.CheckConstraint('nbm_26 BETWEEN 1 AND 4'),
    sa.CheckConstraint('nbm_3  BETWEEN 1 AND 4'),
    sa.CheckConstraint('nbm_4  BETWEEN 1 AND 4'),
    sa.CheckConstraint('nbm_5  BETWEEN 1 AND 4'),
    sa.CheckConstraint('nbm_6  BETWEEN 1 AND 4'),
    sa.CheckConstraint('nbm_7  BETWEEN 1 AND 4'),
    sa.CheckConstraint('nbm_8  BETWEEN 1 AND 4'),
    sa.CheckConstraint('nbm_9  BETWEEN 1 AND 4'),
    sa.ForeignKeyConstraint(['user_email'], ['users.user_email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_nbm_response_user_email', 'nordic_bodymap_response', ['user_email'], unique=False)
    op.create_index(op.f('ix_nordic_bodymap_response_user_email'), 'nordic_bodymap_response', ['user_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nordic_bodymap_response_user_email'), table_name='nordic_bodymap_response')
    op.drop_index('idx_nbm_response_user_email', table_name='nordic_bodymap_response')
    op.drop_table('nordic_bodymap_response')
    # ### end Alembic commands ###
