"""add tlx_response + tlx_factor enum

Revision ID: c8a9c5ef2c34
Revises: 74760e443857
Create Date: 2025-09-05 14:05:34.624480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8a9c5ef2c34'
down_revision: Union[str, Sequence[str], None] = '74760e443857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schemas."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tlx_response',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('pair_q1', postgresql.ENUM('mental', 'physical', 'temporal', 'performance', 'effort', 'frustration', name='tlx_factor'), nullable=False),
    sa.Column('pair_q2', postgresql.ENUM('mental', 'physical', 'temporal', 'performance', 'effort', 'frustration', name='tlx_factor'), nullable=False),
    sa.Column('pair_q3', postgresql.ENUM('mental', 'physical', 'temporal', 'performance', 'effort', 'frustration', name='tlx_factor'), nullable=False),
    sa.Column('pair_q4', postgresql.ENUM('mental', 'physical', 'temporal', 'performance', 'effort', 'frustration', name='tlx_factor'), nullable=False),
    sa.Column('pair_q5', postgresql.ENUM('mental', 'physical', 'temporal', 'performance', 'effort', 'frustration', name='tlx_factor'), nullable=False),
    sa.Column('pair_q6', postgresql.ENUM('mental', 'physical', 'temporal', 'performance', 'effort', 'frustration', name='tlx_factor'), nullable=False),
    sa.Column('pair_q7', postgresql.ENUM('mental', 'physical', 'temporal', 'performance', 'effort', 'frustration', name='tlx_factor'), nullable=False),
    sa.Column('pair_q8', postgresql.ENUM('mental', 'physical', 'temporal', 'performance', 'effort', 'frustration', name='tlx_factor'), nullable=False),
    sa.Column('pair_q9', postgresql.ENUM('mental', 'physical', 'temporal', 'performance', 'effort', 'frustration', name='tlx_factor'), nullable=False),
    sa.Column('pair_q10', postgresql.ENUM('mental', 'physical', 'temporal', 'performance', 'effort', 'frustration', name='tlx_factor'), nullable=False),
    sa.Column('pair_q11', postgresql.ENUM('mental', 'physical', 'temporal', 'performance', 'effort', 'frustration', name='tlx_factor'), nullable=False),
    sa.Column('pair_q12', postgresql.ENUM('mental', 'physical', 'temporal', 'performance', 'effort', 'frustration', name='tlx_factor'), nullable=False),
    sa.Column('pair_q13', postgresql.ENUM('mental', 'physical', 'temporal', 'performance', 'effort', 'frustration', name='tlx_factor'), nullable=False),
    sa.Column('pair_q14', postgresql.ENUM('mental', 'physical', 'temporal', 'performance', 'effort', 'frustration', name='tlx_factor'), nullable=False),
    sa.Column('pair_q15', postgresql.ENUM('mental', 'physical', 'temporal', 'performance', 'effort', 'frustration', name='tlx_factor'), nullable=False),
    sa.Column('likert_mental', sa.SmallInteger(), nullable=False),
    sa.Column('likert_physical', sa.SmallInteger(), nullable=False),
    sa.Column('likert_temporal', sa.SmallInteger(), nullable=False),
    sa.Column('likert_performance_raw', sa.SmallInteger(), nullable=False),
    sa.Column('likert_effort', sa.SmallInteger(), nullable=False),
    sa.Column('likert_frustration', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('likert_effort BETWEEN 1 AND 10', name='ck_likert_effort'),
    sa.CheckConstraint('likert_frustration BETWEEN 1 AND 10', name='ck_likert_frustration'),
    sa.CheckConstraint('likert_mental BETWEEN 1 AND 10', name='ck_likert_mental'),
    sa.CheckConstraint('likert_performance_raw BETWEEN 1 AND 10', name='ck_likert_performance_raw'),
    sa.CheckConstraint('likert_physical BETWEEN 1 AND 10', name='ck_likert_physical'),
    sa.CheckConstraint('likert_temporal BETWEEN 1 AND 10', name='ck_likert_temporal'),
    sa.ForeignKeyConstraint(['user_email'], ['users.user_email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tlx_response_user_email'), 'tlx_response', ['user_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schemas."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tlx_response_user_email'), table_name='tlx_response')
    op.drop_table('tlx_response')
    # ### end Alembic commands ###
